<?php

mb_internal_encoding("UTF-8"); 

# Start a session
session_start();

# Add trailing slash to doc root if needed
if(substr($_SERVER['DOCUMENT_ROOT'], -1) != '/') $_SERVER['DOCUMENT_ROOT'] .= "/";

# Include config file
if($_SERVER['SERVER_NAME'] == "lcrm.testmyhome.com.au") include($_SERVER['DOCUMENT_ROOT'] . 'inc/config.php');
else include('../inc/config.php');

# Include classes
include('../inc/user.class.php');
include('../inc/agency.class.php');
include('../inc/encryption.class.php');
include('../inc/report.class.php');
include('../inc/region.class.php');
include('../inc/sats_crm_class.php');

# Include functions
include('../inc/functions.php');
include('../inc/property_functions.php');
include('../inc/job_functions.php');
include('../inc/alarm_functions.php');

# Include email functions
include('../inc/swiftmailer/lib/swift_required.php');
include('../inc/email_functions.php');

# include library
include('../phpqrcode/qrlib.php');

# Connect to Database
$connection = mysql_connect(HOST, USERNAME, PASSWORD) or die("Could not connect to database:" . mysql_error());
mysql_select_db(DATABASE, $connection) or die("Unable to Select database");

if(UTF8_USED)
{
	#mysql_query("SET NAMES 'utf8'");
}

if(DEV_SITE)
{
	mysql_set_charset('utf8');
}

# Create user object
$user = new User();

# Get the query string stuff
$type = $_GET['t'];
$job_id = intval($_GET['i']);
$md5 = trim($_GET['m']);

# Quit out if not all supplied
if(empty($type) || empty($job_id) || empty($md5)) exit(EXIT_MESSAGE . '1');

if($type != 'i' && $type != 'c' && $type != 'cb') $type = 'i';

# The MD5 is generated by: <type><agencyid><jobid> - type being c [cert] or i [invoice]
# We know the $id from above, so lets get the agency id thats assoicated with that record

$query = mysql_query("
	SELECT p.agency_id 
	FROM property p, jobs j 
	WHERE p.property_id = j.property_id 
	AND j.id = '$job_id' 
	LIMIT 1
");

$result = mysql_fetch_array($query);


# Quit out if no agency id
if(!is_numeric($result['agency_id'])) exit(EXIT_MESSAGE . '2');

$constructed_md5 = md5($type . $result['agency_id'] . $job_id);

if($constructed_md5 != $md5) exit(EXIT_MESSAGE . '3');

# OK so far so print the document
require_once("../inc/fpdf/fpdf.php");
require_once('../inc/fpdf_override.php');

# Get job details
$job_details = getJobDetails2($job_id);


include('../inc/pdfInvoiceCertComb.php');	

# Strip out www from doc root
$_SERVER['DOCUMENT_ROOT'] = str_replace("www", "", $_SERVER['DOCUMENT_ROOT']);
$country_id = $_GET['country_id'];

if($type == 'i')
{
    include("../inc/pdf_invoice_template.php");
    $pdf->Output('invoice' . $job_id . '.pdf', 'I');
}
elseif($type == 'c') 
{
    include("../inc/pdf_certificate_template.php");
    $pdf->Output('cert' . $job_id . '.pdf', 'I');
}
else
{
    include("../inc/pdf_combined_template.php");
    $pdf->Output('cert_invoice' . $job_id . '.pdf', 'I');
}



?>
